"""
Load test for the alerting stack.

Floods the alert receiver webhook with simulated Alertmanager payloads
to prove:
1. Alerts are persisted under sustained load
2. Throughput numbers are documented
3. No alerts are silently dropped
4. Triage background tasks don't block webhook processing
5. Alert delivery latency remains acceptable

Prerequisites:
    docker compose up -d

Run with:
    PYTHONPATH=. uv run pytest tests/integration/test_load_alerting.py -v -s

Note: This test creates many alert_events rows. Consider truncating
      the table before/after for clean runs.
"""

import asyncio
import time
from datetime import datetime, timezone
from uuid import uuid4

import asyncpg
import httpx
import pytest

pytestmark = [pytest.mark.integration, pytest.mark.manual]

ALERT_RECEIVER_URL = "http://localhost:9096"
POSTGRES_DSN = "postgresql://telemetry_user:telemetry_pass@localhost:5432/telemetry"

# ─── Load test parameters ─────────────────────────────────────
# Scenario 1: Sustained webhook load (simulates alerting storm)
ALERTS_PER_SECOND = 100
DURATION_SECONDS = 30
TOTAL_ALERTS = ALERTS_PER_SECOND * DURATION_SECONDS

# Scenario 2: Burst load (simulates cascading failure — many alerts at once)
BURST_SIZE = 500

# Processing timeout — how long to wait for all alerts to be persisted
PROCESSING_TIMEOUT = 30


@pytest.fixture
async def alert_client():
    """HTTP client for the alert receiver."""
    async with httpx.AsyncClient(
        base_url=ALERT_RECEIVER_URL,
        timeout=30.0,
        limits=httpx.Limits(max_connections=50, max_keepalive_connections=25),
    ) as client:
        yield client


@pytest.fixture
async def db_pool():
    """Direct database connection pool for verification."""
    pool = await asyncpg.create_pool(dsn=POSTGRES_DSN, min_size=2, max_size=5)
    yield pool
    await pool.close()


def _make_batch_payload(
    batch_size: int,
    severity: str = "warning",
    prefix: str = "load-test",
) -> dict:
    """
    Build an Alertmanager webhook payload with multiple alerts.
    Each alert has a unique fingerprint.
    """
    now = datetime.now(timezone.utc).isoformat()
    alerts = []
    for i in range(batch_size):
        alerts.append({
            "status": "firing",
            "labels": {
                "alertname": f"LoadTest_{prefix}_{i}",
                "severity": severity,
                "pipeline": "test",
                "tier": "platform",
                "instance": f"load-test-{i}",
            },
            "annotations": {
                "summary": f"Load test alert {i}",
                "description": f"Generated by load test at {now}",
            },
            "startsAt": now,
            "endsAt": "0001-01-01T00:00:00Z",
            "generatorURL": "http://prometheus:9090/load-test",
            "fingerprint": f"{prefix}-{uuid4().hex[:12]}",
        })

    return {
        "version": "4",
        "groupKey": f"{prefix}-group",
        "truncatedAlerts": 0,
        "status": "firing",
        "receiver": "webhook-all",
        "groupLabels": {"alertname": f"LoadTest_{prefix}"},
        "commonLabels": {"severity": severity},
        "commonAnnotations": {},
        "externalURL": "http://alertmanager:9093",
        "alerts": alerts,
    }


class TestAlertingLoadPerformance:
    """
    Load test: verify the alerting pipeline handles sustained throughput
    without dropping alerts or degrading response times.
    """

    async def test_sustained_webhook_throughput(self, alert_client, db_pool):
        """
        Send 100 alerts/sec for 30 seconds (3000 total).
        Verify all alerts are persisted and measure throughput.
        """
        print(f"\n{'='*60}")
        print(f"  SUSTAINED LOAD TEST")
        print(f"  Target: {ALERTS_PER_SECOND} alerts/sec for {DURATION_SECONDS}s")
        print(f"  Total: {TOTAL_ALERTS} alerts")
        print(f"{'='*60}")

        # Baseline count
        async with db_pool.acquire() as conn:
            baseline = await conn.fetchval("SELECT COUNT(*) FROM alert_events")

        # --- Send phase ---
        sent_count = 0
        accepted_count = 0
        error_count = 0
        latencies = []
        start_time = time.time()

        # Send in batches of 10 per request (simulating grouped alerts)
        batch_size = 10
        requests_per_second = ALERTS_PER_SECOND // batch_size

        for second in range(DURATION_SECONDS):
            second_start = time.time()
            tasks = []

            for req_idx in range(requests_per_second):
                prefix = f"sustained-s{second}-r{req_idx}"
                payload = _make_batch_payload(
                    batch_size=batch_size,
                    severity="warning",
                    prefix=prefix,
                )
                tasks.append(self._timed_post(alert_client, payload))

            results = await asyncio.gather(*tasks, return_exceptions=True)

            for result in results:
                if isinstance(result, Exception):
                    error_count += batch_size
                else:
                    status_code, response_time, body = result
                    latencies.append(response_time)
                    if status_code == 202:
                        accepted_count += body.get("processed", 0)
                        error_count += body.get("errors", 0)
                    else:
                        error_count += batch_size

            sent_count += requests_per_second * batch_size

            # Pace to target rate
            elapsed = time.time() - second_start
            if elapsed < 1.0:
                await asyncio.sleep(1.0 - elapsed)

            # Progress every 10s
            if (second + 1) % 10 == 0:
                total_elapsed = time.time() - start_time
                rate = accepted_count / total_elapsed
                p95 = sorted(latencies)[int(len(latencies) * 0.95)] if latencies else 0
                print(f"    [{second+1:3d}s] accepted={accepted_count}, rate={rate:.0f}/s, p95={p95*1000:.0f}ms")

        total_time = time.time() - start_time

        # --- Wait for persistence ---
        print(f"\n  Waiting up to {PROCESSING_TIMEOUT}s for DB persistence...")
        await asyncio.sleep(3)  # Give background tasks time to complete

        async with db_pool.acquire() as conn:
            final_count = await conn.fetchval("SELECT COUNT(*) FROM alert_events")

        new_alerts = final_count - baseline

        # --- Report ---
        latencies.sort()
        p50 = latencies[int(len(latencies) * 0.50)] * 1000 if latencies else 0
        p95 = latencies[int(len(latencies) * 0.95)] * 1000 if latencies else 0
        p99 = latencies[int(len(latencies) * 0.99)] * 1000 if latencies else 0
        actual_rate = accepted_count / total_time

        print(f"\n  {'─'*50}")
        print(f"  RESULTS: Sustained Load")
        print(f"  {'─'*50}")
        print(f"  Sent:           {sent_count} alerts")
        print(f"  Accepted:       {accepted_count} alerts")
        print(f"  Errors:         {error_count}")
        print(f"  Persisted (DB): {new_alerts}")
        print(f"  Duration:       {total_time:.1f}s")
        print(f"  Throughput:     {actual_rate:.0f} alerts/sec")
        print(f"  Latency p50:    {p50:.0f}ms")
        print(f"  Latency p95:    {p95:.0f}ms")
        print(f"  Latency p99:    {p99:.0f}ms")
        print(f"  Drop rate:      {(1 - new_alerts/max(accepted_count,1))*100:.2f}%")
        print(f"  {'─'*50}")

        # Assertions — no more than 1% dropped
        assert accepted_count > 0, "No alerts were accepted"
        assert error_count / max(sent_count, 1) < 0.05, f"Error rate too high: {error_count}/{sent_count}"
        assert new_alerts >= accepted_count * 0.99, f"Dropped alerts: {accepted_count - new_alerts}"
        assert p95 < 5000, f"p95 latency too high: {p95:.0f}ms (max 5000ms)"

    async def test_burst_load(self, alert_client, db_pool):
        """
        Send 500 alerts in a single webhook request.
        Simulates a cascading failure scenario where many alerts fire simultaneously.
        """
        print(f"\n{'='*60}")
        print(f"  BURST LOAD TEST")
        print(f"  Single request with {BURST_SIZE} alerts")
        print(f"{'='*60}")

        async with db_pool.acquire() as conn:
            baseline = await conn.fetchval("SELECT COUNT(*) FROM alert_events")

        # Send one massive batch
        payload = _make_batch_payload(
            batch_size=BURST_SIZE,
            severity="critical",
            prefix="burst-test",
        )

        start = time.time()
        response = await alert_client.post("/alerts", json=payload)
        latency = time.time() - start

        assert response.status_code == 202
        body = response.json()

        # Wait for DB
        await asyncio.sleep(3)

        async with db_pool.acquire() as conn:
            final_count = await conn.fetchval("SELECT COUNT(*) FROM alert_events")

        new_alerts = final_count - baseline

        print(f"\n  {'─'*50}")
        print(f"  RESULTS: Burst Load")
        print(f"  {'─'*50}")
        print(f"  Batch size:     {BURST_SIZE} alerts")
        print(f"  Processed:      {body['processed']}")
        print(f"  Errors:         {body['errors']}")
        print(f"  Persisted (DB): {new_alerts}")
        print(f"  Response time:  {latency*1000:.0f}ms")
        print(f"  Per-alert:      {latency*1000/BURST_SIZE:.1f}ms/alert")
        print(f"  {'─'*50}")

        assert body["processed"] == BURST_SIZE
        assert body["errors"] == 0
        assert new_alerts == BURST_SIZE
        # Single batch should complete in < 30s even with 500 alerts
        assert latency < 30, f"Burst took too long: {latency:.1f}s"

    async def test_concurrent_webhooks(self, alert_client, db_pool):
        """
        Send 50 concurrent webhook requests each with 10 alerts.
        Proves the receiver handles concurrent connections gracefully.
        """
        print(f"\n{'='*60}")
        print(f"  CONCURRENT WEBHOOKS TEST")
        print(f"  50 concurrent requests × 10 alerts = 500 alerts")
        print(f"{'='*60}")

        async with db_pool.acquire() as conn:
            baseline = await conn.fetchval("SELECT COUNT(*) FROM alert_events")

        concurrent_requests = 50
        alerts_per_request = 10

        tasks = []
        for i in range(concurrent_requests):
            payload = _make_batch_payload(
                batch_size=alerts_per_request,
                severity="info",
                prefix=f"concurrent-{i}",
            )
            tasks.append(self._timed_post(alert_client, payload))

        start = time.time()
        results = await asyncio.gather(*tasks, return_exceptions=True)
        total_time = time.time() - start

        # Analyze results
        total_processed = 0
        total_errors = 0
        latencies = []
        request_errors = 0

        for result in results:
            if isinstance(result, Exception):
                request_errors += 1
            else:
                status_code, response_time, body = result
                latencies.append(response_time)
                if status_code == 202:
                    total_processed += body.get("processed", 0)
                    total_errors += body.get("errors", 0)
                else:
                    request_errors += 1

        await asyncio.sleep(2)

        async with db_pool.acquire() as conn:
            final_count = await conn.fetchval("SELECT COUNT(*) FROM alert_events")

        new_alerts = final_count - baseline
        latencies.sort()
        p50 = latencies[int(len(latencies) * 0.50)] * 1000 if latencies else 0
        p95 = latencies[int(len(latencies) * 0.95)] * 1000 if latencies else 0

        print(f"\n  {'─'*50}")
        print(f"  RESULTS: Concurrent Webhooks")
        print(f"  {'─'*50}")
        print(f"  Requests:       {concurrent_requests}")
        print(f"  Alerts/req:     {alerts_per_request}")
        print(f"  Total processed:{total_processed}")
        print(f"  Request errors: {request_errors}")
        print(f"  Alert errors:   {total_errors}")
        print(f"  Persisted (DB): {new_alerts}")
        print(f"  Total time:     {total_time*1000:.0f}ms")
        print(f"  Latency p50:    {p50:.0f}ms")
        print(f"  Latency p95:    {p95:.0f}ms")
        print(f"  {'─'*50}")

        expected = concurrent_requests * alerts_per_request
        assert request_errors == 0, f"{request_errors} requests failed"
        assert total_processed == expected
        assert new_alerts >= expected * 0.99

    async def test_triage_does_not_block_webhook(self, alert_client):
        """
        Send a critical alert (triggers triage) and verify the webhook
        response time is not affected by the triage background task.
        The webhook should return immediately; triage runs async.
        """
        print(f"\n{'='*60}")
        print(f"  TRIAGE NON-BLOCKING TEST")
        print(f"{'='*60}")

        # Send a critical alert that triggers triage
        payload = _make_batch_payload(
            batch_size=1,
            severity="critical",
            prefix=f"triage-timing-{uuid4().hex[:6]}",
        )
        # Override alert name to trigger triage
        payload["alerts"][0]["labels"]["alertname"] = "ServiceDown"

        start = time.time()
        response = await alert_client.post("/alerts", json=payload)
        latency = time.time() - start

        assert response.status_code == 202

        print(f"\n  Critical alert webhook response: {latency*1000:.0f}ms")
        print(f"  (Triage runs in background — should not add latency)")

        # Webhook should respond in < 2s regardless of triage
        # (triage takes 0-30s for LLM, but is fire-and-forget)
        assert latency < 2.0, f"Webhook blocked by triage: {latency:.1f}s"

    # ─── Helper ───────────────────────────────────────────────

    @staticmethod
    async def _timed_post(client, payload) -> tuple[int, float, dict]:
        """POST with timing. Returns (status_code, duration_seconds, body)."""
        start = time.time()
        response = await client.post("/alerts", json=payload)
        duration = time.time() - start
        return response.status_code, duration, response.json()
